spring:
  application:
    name: wxchat-cloud-server
  datasource:
    url: jdbc:mysql://localhost:3306/test?useOldAliasMetadataBehavior=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

logging:
  file: logs/${spring.application.name}.log
  level:
    root: info
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.jdbc.core.StatementCreatorUtils: trace